export const clubsAbbriviations = {
  Arsenal: "ARS",
  "Aston Villa": "AVL",
  Brentford: "BRE",
  Bournemouth: "BOU",
  "Brighton & Hove Albion": "BRI",
  Brighton: "BRI",
  Blackburn: "BBN",
  Burnley: "BUR",
  Chelsea: "CHE",
  "Crystal Palace": "CRY",
  Fulham: "FUL",
  Everton: "EVE",
  "Luton Town": "LUT",
  Liverpool: "LIV",
  "Manchester City": "MCI",
  "Man City": "MCI",
  "Bristol C": "BSC",
  Stoke: "STK",
  "Manchester United": "MUN",
  "Newcastle United": "NEW",
  "Sheffield United": "SHU",
  Spurs: "TOT",
  "West Ham United": "WHU",
  "Wolverhampton Wanderers": "WOL",
  "Nottingham Forest": "NFO",
  Leeds: "LEE",
  Southampton: "SOU",
  Leicester: "LEI",
};
